### ISSUE TITLE
想翻譯這幾行

### ISSUE THREAD

**Issue by RillRill** [Meowurs/TreeOfSaviorChineseTraditional#12]
餓死抬頭
ITEM.tsv
2360-2460

**Comment by rftsubaki** [comment]
您好，我是負責item的RF

由於魔物名稱尚未定案
所以能請您先把魔物名稱保持原文嗎?
日後會再一次取代

麻煩您了  謝謝

**Comment by RillRill** [comment]
收到，
有些已經翻譯中文的我就沿用了!
感謝告知
