### ISSUE TITLE
翻譯小錯誤(附圖)

### ISSUE THREAD

**Issue by darkmiz** [Meowurs/TreeOfSaviorChineseTraditional#3]
如圖，"治癒"應改為"輔助"，"申請中."應改為"使用中"並去掉句點
![a1](https://cloud.githubusercontent.com/assets/15335968/10808895/7a17a628-7e2b-11e5-976c-5be07c8ce6eb.jpg)
![a2](https://cloud.githubusercontent.com/assets/15335968/10808896/7a1ad8e8-7e2b-11e5-82c4-16c9b5cb9b6b.jpg)

**Comment by miaulightouch** [comment]
圖文部分請回應至巴哈姆特討論串，這邊的話比較適合 文字糾錯

**Comment by miaulightouch** [comment]
已幫你反映給負責的翻譯。

**Comment by nickexe** [comment]
我覺得他這個 issue 發的很好，這才是 issue 的正規用法，
看到的人去修正錯誤，留下 commit，並在註解寫上 issue 編號，
一眼就可以知道 commit 是解決那個問題。
整個問題的發現到解決的脈絡可以被記錄下來。
然後解決之後就可以把 issue 給 close。
還沒 close 的就可以當成 todo list。

**Comment by miaulightouch** [comment]
喔喔喔！感謝NICK大提點。
這樣感覺的確快多了。

**Comment by miaulightouch** [comment]
本 issue 已透過Commit 修正，請見以下
Commit: 4981e7578edaeadf96666124a0dacbb83266b638
