### ISSUE TITLE
可以更新一下QUEST_LV_0100.tsv中文翻譯最新版嗎

### ISSUE THREAD

**Issue by darkmiz** [Meowurs/TreeOfSaviorChineseTraditional#4]
我想先翻譯任務的部分，麻煩上傳最新的QUEST_LV_0100.tsv中文翻譯版

**Comment by miaulightouch** [comment]
目前QUSET_LV_0100.tsv 組內正有人著手翻譯了，怕您會重覆翻譯。

本github目前還在購建中，您可以待我們全部更新至github後，做輔助翻譯校正。
