### ISSUE TITLE
好奇問一下

### ISSUE THREAD

**Issue by darkmiz** [Meowurs/TreeOfSaviorChineseTraditional#5]
請問管理員miau大跟ishanah是同一人嗎
還有其他成員共有哪些呢

**Comment by miaulightouch** [comment]
不是同一人，另外的成員我不曉得他們的巴哈ID是什麼。
不過對外接洽事由他這邊負責，包含對簡中翻譯團隊的交流也是。

**Comment by darkmiz** [comment]
簡中翻譯團隊是中國代理商官方的翻譯團隊嗎？

**Comment by miaulightouch** [comment]
這部分我也不清楚，您可能要直接去問小空。
畢竟接洽是由他負責的。
